# Generated by Django 6.0.5 on 2026-05-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlalgorithmstatus",
            name="parent_mlalgorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="endpoints.mlalgorithm",
            ),
        ),
    ]
