# Generated by Django 6.0.5 on 2026-05-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0002_mlalgorithmstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MLAlgorithmStatus",
        ),
    ]
